### ISSUE TITLE
PWA and WEB Pushnotifactions 

### ISSUE THREAD

**Issue by prema1432** [nimaes80/django-simple-pwa#4]
@nimaes80 hi, how can we send push notifications using this library? or we can use any other library for Push Notifications for the web and PWA

**Comment by nimaes80** [comment]
At first I should mention that push notification doesn't related to PWA however if you want to send you notifications to your app you can use Django channels if you want to send push notification to your app you should use Google push notification or something similar then if you want to send something to your users used used you send a request and Google send the vacation to your Django app I'm trying to create a push notification server Django but it seems it's not available at this moment because everything has a unique ID that we don't have access to that but Google and other services can access to that ID I'm researching about this in in these days but I don't have find any information about that how we can access to that unique ID. If I can find anything about that in future I create a push Notification Service for a jungle and you can use it but at now you can't use this library or other libraries to send a push notification to Django they are only few library/app that you can use them to send push notif but only as a proxy not a server.
